apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-gitops-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jlui70/argocd-gitops-demo.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
